services:
  gphotos-uploader:
    build: .
    container_name: gphotos-uploader
    restart: unless-stopped
    environment:
      - WATCHED_FOLDER=/data
      - AUTH_DATA=androidId=36c790a4b419a087&app=com.google.android.apps.photos&client_sig=24bb24c05e47e0aefa68a58a766179d9b613a600&callerPkg=com.google.android.apps.photos&callerSig=24bb24c05e47e0aefa68a58a766179d9b613a600&device_country=us&Email=endrisusanto2026%40gmail.com&google_play_services_version=250932000&lang=en_US&oauth2_foreground=1&operatorCountry=us&sdk_version=36&service=oauth2%3Aopenid%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fmobileapps.native%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fphotos.native&source=android&Token=aas_et%2FAKppINYa-6LvQt9qNF4v1V_3KeKtABAPMmmlG2O_GfPuxZ4O0xswob59xqB8xjAXX6WPzn-plnx61QNP-Da11aqLnLXzIBWXbPj1VSiAUrWWv5dMEocjSbq0q-Aflb7u2tmgnOdiLTn2kvezpF2EvbNSLRKUzhalfh4wrHT8ugIb18NSa6sxBk9NYc2tVurFGXfTNss1MLAnEtUzh9QRBpA%3D
    security_opt:
      - label:disable
    volumes:
      - /home/endri-pro/Desktop/Google/:/data:z
      - ./script_gphoto.py:/app/script_gphoto.py:z
      - ./index.html:/app/index.html:z
    ports:
      - "8080:8080"
